management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: SB-JWT-Author_Authent
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/userjwt
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
